openapi: 3.0.0
info:
  title: API Demo Form Tests October 21
  version: 1.0.0
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
paths:
  /rm-1-rm/services/oauth2/token:
    post:
      tags:
        - default
      summary: Login - get access token
      requestBody:
        content: {}
      security:
        - noauthAuth: []
      parameters:
        - name: ''
          in: header
          schema:
            type: string
        - name: grant_type
          in: query
          schema:
            type: string
          example: password
        - name: client_id
          in: query
          schema:
            type: string
          example: '{{clientid}}'
        - name: client_secret
          in: query
          schema:
            type: string
          example: '{{client_secret}}'
        - name: username
          in: query
          schema:
            type: string
          example: '{{username}}'
        - name: password
          in: query
          schema:
            type: string
          example: '{{password}}{{token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-2-rm/services/apexrest/formdata/v1:
    put:
      tags:
        - default
      summary: Form - upsert one form
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                records:
                  - externalId: '{{formtimestamp}}'
                    id: ''
                    name: demo {{formtimestamp}}
                    alias: demo {{formtimestamp}}
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on {{$timestamp}}
                    status: Draft
                    formVersion:
                      - versionid: ''
                        changeLogNumber: ''
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutFormData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-3-rm/services/apexrest/formdata/v1:
    put:
      tags:
        - default
      summary: Form - upsert multiple forms
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                records:
                  - externalId: '{{formtimestamp}}-1'
                    id: ''
                    name: demo {{formtimestamp}}-1
                    alias: demo {{formtimestamp}}-1
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on {{$timestamp}}
                    status: Draft
                    formVersion:
                      - versionid: ''
                        changeLogNumber: ''
                  - externalId: '{{formtimestamp}}-2'
                    id: ''
                    name: demo {{formtimestamp}}-2
                    alias: demo {{formtimestamp}}-2
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on {{$timestamp}}
                    status: Draft
                    formVersion:
                      - versionid: ''
                        changeLogNumber: ''
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutFormData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-4-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Form - get by ID
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: id
          in: query
          schema:
            type: string
          example: '{{new_form_id}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-5-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Form - get by Name
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: name
          in: query
          schema:
            type: string
          example: demo {{formtimestamp}}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-6-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Form - get by limit and offset
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: startNumber
          in: query
          schema:
            type: integer
          example: '0'
        - name: endNumber
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-7-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Create Section
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n \"records\": [\r\n {\r\n \"externalId\": \"S1\",\r\n
                \"id\": \"\",\r\n \"name\": \"section a\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"Section A\",\r\n \"cascadingLevel\": \"\",\r\n \"options\":
                [],\r\n \"cascadingSelect\": \"\",\r\n \"controllingQuestion\":
                \"\",\r\n \"displayRepeatSectionInTable\": false,\r\n
                \"doAfter\": \"\",\r\n \"doBefore\": \"\",\r\n
                \"dynamicOperationType\": \"\",\r\n \"exampleOfValidResponse\":
                \"\",\r\n \"firstVersion\": 1,\r\n \"form\":
                \"{{newly_created_form_id}}\",\r\n \"formVersion\":
                \"{{current_form_versionid}}\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"\",\r\n
                \"position\": 1,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"section\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"{{current_form_change_log_number}}\"\r\n }\r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-8-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Create Question
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n \"records\": [\r\n {\r\n \"externalId\": \"Q1\",\r\n
                \"id\": \"\",\r\n \"name\": \"enter_your_age\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"enter_your_age\",\r\n \"cascadingLevel\": \"\",\r\n
                \"options\": [],\r\n \"cascadingSelect\": \"\",\r\n
                \"controllingQuestion\": \"\",\r\n
                \"displayRepeatSectionInTable\": false,\r\n \"doAfter\":
                \"\",\r\n \"doBefore\": \"\",\r\n \"dynamicOperationType\":
                \"\",\r\n \"exampleOfValidResponse\": \"\",\r\n
                \"firstVersion\": 1,\r\n \"form\": \"a0h5g000002zEH9AAM\",\r\n
                \"formVersion\": \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"S1\",\r\n
                \"position\": 1,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\":
                \"number-integer\",\r\n \"useCurrentTimeAsDefault\": false,\r\n
                \"changeLogNumber\": \"0\"\r\n }\r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-9-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Create Repeat Section
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n \"records\": [\r\n {\r\n \"externalId\": \"RS1\",\r\n
                \"id\": \"\",\r\n \"name\": \"RepeatSection\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"RepeatSection\",\r\n \"cascadingLevel\": \"\",\r\n
                \"options\": [],\r\n \"cascadingSelect\": \"\",\r\n
                \"controllingQuestion\": \"\",\r\n
                \"displayRepeatSectionInTable\": true,\r\n \"doAfter\":
                \"\",\r\n \"doBefore\": \"\",\r\n \"dynamicOperationType\":
                \"\",\r\n \"exampleOfValidResponse\": \"\",\r\n
                \"firstVersion\": 1,\r\n \"form\": \"a0h5g000002zEH9AAM\",\r\n
                \"formVersion\": \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"\",\r\n
                \"position\": 2,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"Q1\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                true,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"repeat\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"0\"\r\n }\r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-10-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Create Question with Options
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n \"records\": [\r\n {\r\n \"externalId\": \"Q2\",\r\n
                \"id\": \"\",\r\n \"name\": \"gender\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"gender\",\r\n \"cascadingLevel\": \"\",\r\n \"options\": [\r\n
                {\r\n \"externalId\": \"O1\",\r\n \"id\": \"\",\r\n \"name\":
                \"male\",\r\n \"position\": 1,\r\n \"caption\": \"male\"\r\n
                },{\r\n \"externalId\": \"O2\",\r\n \"id\": \"\",\r\n \"name\":
                \"female\",\r\n \"position\": 2,\r\n \"caption\": \"female\"\r\n
                },{\r\n \"externalId\": \"O3\",\r\n \"id\": \"\",\r\n \"name\":
                \"other\",\r\n \"position\": 3,\r\n \"caption\": \"other\"\r\n
                }\r\n ],\r\n \"cascadingSelect\": \"\",\r\n
                \"controllingQuestion\": \"\",\r\n
                \"displayRepeatSectionInTable\": false,\r\n \"doAfter\":
                \"\",\r\n \"doBefore\": \"\",\r\n \"dynamicOperationType\":
                \"\",\r\n \"exampleOfValidResponse\": \"\",\r\n
                \"firstVersion\": 1,\r\n \"form\": \"a0h5g000002zEH9AAM\",\r\n
                \"formVersion\": \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"S1\",\r\n
                \"position\": 2,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"radio\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"0\"\r\n }\r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-11-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Create Multiple Questions
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n \"records\": [\r\n {\r\n \"externalId\": \"S1\",\r\n
                \"id\": \"\",\r\n \"name\": \"section a\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"Section A\",\r\n \"cascadingLevel\": \"\",\r\n \"options\":
                [],\r\n \"cascadingSelect\": \"\",\r\n \"controllingQuestion\":
                \"\",\r\n \"displayRepeatSectionInTable\": false,\r\n
                \"doAfter\": \"\",\r\n \"doBefore\": \"\",\r\n
                \"dynamicOperationType\": \"\",\r\n \"exampleOfValidResponse\":
                \"\",\r\n \"firstVersion\": 1,\r\n \"form\":
                \"a0h5g000002zEH9AAM\",\r\n \"formVersion\":
                \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n \"lastVersion\":
                1,\r\n \"maximum\": \"\",\r\n \"maxInstance\": 0,\r\n
                \"minimum\": \"\",\r\n \"parent\": \"\",\r\n \"position\":
                1,\r\n \"ppiResultField\": \"\",\r\n \"previousVersion\":
                \"\",\r\n \"printAnswer\": false,\r\n \"remoteId\": \"\",\r\n
                \"remoteLibrary\": \"\",\r\n \"remoteServerId\": \"\",\r\n
                \"repeatSourceValue\": \"\",\r\n \"repeatTimes\": \"\",\r\n
                \"required\": true,\r\n \"responseValidation\": \"\",\r\n
                \"showAllQuestionOnOnePage\": false,\r\n \"skipLogicBehavior\":
                \"Show\",\r\n \"skipLogicOperator\": \"All\",\r\n \"hint\":
                \"\",\r\n \"testDynamicOperation\": false,\r\n \"type\":
                \"section\",\r\n \"useCurrentTimeAsDefault\": false,\r\n
                \"changeLogNumber\": \"0\"\r\n },\r\n {\r\n \"externalId\":
                \"Q1\",\r\n \"id\": \"\",\r\n \"name\": \"enter_your_age\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"enter_your_age\",\r\n \"cascadingLevel\": \"\",\r\n
                \"options\": [],\r\n \"cascadingSelect\": \"\",\r\n
                \"controllingQuestion\": \"\",\r\n
                \"displayRepeatSectionInTable\": false,\r\n \"doAfter\":
                \"\",\r\n \"doBefore\": \"\",\r\n \"dynamicOperationType\":
                \"\",\r\n \"exampleOfValidResponse\": \"\",\r\n
                \"firstVersion\": 1,\r\n \"form\": \"a0h5g000002zEH9AAM\",\r\n
                \"formVersion\": \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"S1\",\r\n
                \"position\": 1,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\":
                \"number-integer\",\r\n \"useCurrentTimeAsDefault\": false,\r\n
                \"changeLogNumber\": \"0\"\r\n },\r\n {\r\n \"externalId\":
                \"RS1\",\r\n \"id\": \"\",\r\n \"name\": \"RepeatSection\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"RepeatSection\",\r\n \"cascadingLevel\": \"\",\r\n
                \"options\": [],\r\n \"cascadingSelect\": \"\",\r\n
                \"controllingQuestion\": \"\",\r\n
                \"displayRepeatSectionInTable\": true,\r\n \"doAfter\":
                \"\",\r\n \"doBefore\": \"\",\r\n \"dynamicOperationType\":
                \"\",\r\n \"exampleOfValidResponse\": \"\",\r\n
                \"firstVersion\": 1,\r\n \"form\": \"a0h5g000002zEH9AAM\",\r\n
                \"formVersion\": \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"\",\r\n
                \"position\": 2,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"Q1\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                true,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"repeat\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"0\"\r\n },\r\n {\r\n \"externalId\": \"RSQ1\",\r\n \"id\":
                \"\",\r\n \"name\": \"address\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"address\",\r\n \"cascadingLevel\": \"\",\r\n \"options\":
                [],\r\n \"cascadingSelect\": \"\",\r\n \"controllingQuestion\":
                \"\",\r\n \"displayRepeatSectionInTable\": false,\r\n
                \"doAfter\": \"\",\r\n \"doBefore\": \"\",\r\n
                \"dynamicOperationType\": \"\",\r\n \"exampleOfValidResponse\":
                \"\",\r\n \"firstVersion\": 1,\r\n \"form\":
                \"a0h5g000002zEH9AAM\",\r\n \"formVersion\":
                \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n \"lastVersion\":
                1,\r\n \"maximum\": \"\",\r\n \"maxInstance\": 0,\r\n
                \"minimum\": \"\",\r\n \"parent\": \"RS1\",\r\n \"position\":
                1,\r\n \"ppiResultField\": \"\",\r\n \"previousVersion\":
                \"\",\r\n \"printAnswer\": false,\r\n \"remoteId\": \"\",\r\n
                \"remoteLibrary\": \"\",\r\n \"remoteServerId\": \"\",\r\n
                \"repeatSourceValue\": \"\",\r\n \"repeatTimes\": \"\",\r\n
                \"required\": true,\r\n \"responseValidation\": \"\",\r\n
                \"showAllQuestionOnOnePage\": false,\r\n \"skipLogicBehavior\":
                \"Show\",\r\n \"skipLogicOperator\": \"All\",\r\n \"hint\":
                \"\",\r\n \"testDynamicOperation\": false,\r\n \"type\":
                \"text-long\",\r\n \"useCurrentTimeAsDefault\": false,\r\n
                \"changeLogNumber\": \"0\"\r\n },\r\n {\r\n \"externalId\":
                \"Q2\",\r\n \"id\": \"\",\r\n \"name\": \"gender\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"gender\",\r\n \"cascadingLevel\": \"\",\r\n \"options\": [\r\n
                {\r\n \"externalId\": \"O1\",\r\n \"id\": \"\",\r\n \"name\":
                \"male\",\r\n \"position\": 1,\r\n \"caption\": \"male\"\r\n
                },{\r\n \"externalId\": \"O2\",\r\n \"id\": \"\",\r\n \"name\":
                \"female\",\r\n \"position\": 2,\r\n \"caption\": \"female\"\r\n
                }\r\n ],\r\n \"cascadingSelect\": \"\",\r\n
                \"controllingQuestion\": \"\",\r\n
                \"displayRepeatSectionInTable\": false,\r\n \"doAfter\":
                \"\",\r\n \"doBefore\": \"\",\r\n \"dynamicOperationType\":
                \"\",\r\n \"exampleOfValidResponse\": \"\",\r\n
                \"firstVersion\": 1,\r\n \"form\": \"a0h5g000002zEH9AAM\",\r\n
                \"formVersion\": \"a0g5g000002OHzM\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"S1\",\r\n
                \"position\": 2,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"radio\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"0\"\r\n }\r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-12-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Create Questions for existing Section
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n \"records\": [\r\n {\r\n \"externalId\":\"S1\",\r\n
                \"id\": \"a0S5g0000010rfwEAA\",\r\n \"name\": \"section a\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"Section A\",\r\n \"cascadingLevel\": \"\",\r\n
                \"cascadingSelect\": \"\",\r\n \"controllingQuestion\":
                \"\",\r\n \"displayRepeatSectionInTable\": false,\r\n
                \"doAfter\": \"\",\r\n \"doBefore\": \"\",\r\n
                \"dynamicOperationType\": \"\",\r\n \"exampleOfValidResponse\":
                \"\",\r\n \"firstVersion\": 1,\r\n \"form\":
                \"a0h5g000002zEH9AAM\",\r\n \"formVersion\":
                \"a0g5g000002OHzMAAW\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": \"\",\r\n \"maximum\": 0.000000,\r\n
                \"maxInstance\": 0,\r\n \"minimum\": 0.000000,\r\n \"parent\":
                \"\",\r\n \"position\": 1,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"section\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"4\",\r\n \"options\": []\r\n },\r\n {\r\n \"externalId\":
                \"Q3\",\r\n \"id\": \"\",\r\n \"name\":
                \"enter_your_Occupation\",\r\n \"canbeDownloadedInTheEditForm\":
                false,\r\n \"caption\": \"enter_your_Occupation\",\r\n
                \"cascadingLevel\": \"\",\r\n \"options\": [],\r\n
                \"cascadingSelect\": \"\",\r\n \"controllingQuestion\":
                \"\",\r\n \"displayRepeatSectionInTable\": false,\r\n
                \"doAfter\": \"\",\r\n \"doBefore\": \"\",\r\n
                \"dynamicOperationType\": \"\",\r\n \"exampleOfValidResponse\":
                \"\",\r\n \"firstVersion\": 1,\r\n \"form\":
                \"a0h5g000002zEH9AAM\",\r\n \"formVersion\":
                \"a0g5g000002OHzMAAW\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": 1,\r\n \"maximum\": \"\",\r\n \"maxInstance\":
                0,\r\n \"minimum\": \"\",\r\n \"parent\": \"S1\",\r\n
                \"position\": 3,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                false,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\":
                \"text-long\",\r\n \"useCurrentTimeAsDefault\": false,\r\n
                \"changeLogNumber\": \"4\"\r\n }\r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-13-rm/services/apexrest/questiondata/v1:
    put:
      tags:
        - default
      summary: Question - Update Repeat Section
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\"records\": [\r\n {\r\n \"externalId\":\"RS1\",\r\n \"id\":
                \"a0S5g0000010rfzEAA\",\r\n \"name\": \"RepeatSection\",\r\n
                \"canbeDownloadedInTheEditForm\": false,\r\n \"caption\":
                \"RepeatSection\",\r\n \"cascadingLevel\": \"\",\r\n
                \"cascadingSelect\": \"\",\r\n \"controllingQuestion\":
                \"\",\r\n \"displayRepeatSectionInTable\": true,\r\n
                \"doAfter\": \"\",\r\n \"doBefore\": \"\",\r\n
                \"dynamicOperationType\": \"\",\r\n \"exampleOfValidResponse\":
                \"\",\r\n \"firstVersion\": 1,\r\n \"form\":
                \"a0h5g000002zEH9AAM\",\r\n \"formVersion\":
                \"a0g5g000002OHzMAAW\",\r\n \"hidden\": false,\r\n
                \"lastVersion\": \"\",\r\n \"maximum\": 0.000000,\r\n
                \"maxInstance\": 0,\r\n \"minimum\": 0.000000,\r\n \"parent\":
                \"\",\r\n \"position\": 2,\r\n \"ppiResultField\": \"\",\r\n
                \"previousVersion\": \"\",\r\n \"printAnswer\": false,\r\n
                \"remoteId\": \"\",\r\n \"remoteLibrary\": \"\",\r\n
                \"remoteServerId\": \"\",\r\n \"repeatSourceValue\": \"\",\r\n
                \"repeatTimes\": \"3\",\r\n \"required\": true,\r\n
                \"responseValidation\": \"\",\r\n \"showAllQuestionOnOnePage\":
                true,\r\n \"skipLogicBehavior\": \"Show\",\r\n
                \"skipLogicOperator\": \"All\",\r\n \"hint\": \"\",\r\n
                \"testDynamicOperation\": false,\r\n \"type\": \"repeat\",\r\n
                \"useCurrentTimeAsDefault\": false,\r\n \"changeLogNumber\":
                \"5\",\r\n \"options\": []\r\n }\r\n \r\n ]\r\n}"
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutQuestionData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-14-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Question - get by ID
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: id
          in: query
          schema:
            type: string
          example: a0h4w00000QwnWTAAZ
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-15-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Question - get by limit and offset
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: startNumber
          in: query
          schema:
            type: integer
          example: '0'
        - name: endNumber
          in: query
          schema:
            type: integer
          example: '17'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-16-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Exception - bad request
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: startNumber
          in: query
          schema:
            type: string
          example: 0...
        - name: endNumber
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-17-rm/services/apexrest/formdata/v1123:
    get:
      tags:
        - default
      summary: Exception - invalid URL
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData
        - name: startNumber
          in: query
          schema:
            type: integer
          example: '0'
        - name: endNumber
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-18-rm/services/apexrest/formdata/v1:
    get:
      tags:
        - default
      summary: Exception - JSON Mapping Not Found
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: GetFormData123
        - name: startNumber
          in: query
          schema:
            type: integer
          example: '0'
        - name: endNumber
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-19-rm/services/apexrest/formdata/v1:
    put:
      tags:
        - default
      summary: Exception - url not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                records:
                  - externalId: '123'
                    id: ''
                    name: a100000
                    alias: a100000
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 4th Oct
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OBs7AAG
                        changeLogNumber: '0'
                  - externalId: '234'
                    id: a0h5g000002z4fVAAQ
                    name: a10010
                    alias: a10010
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 4th Oct
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OBtZAAW
                        changeLogNumber: '1'
                  - externalId: '345'
                    id: a0h5g000002zARTAA2
                    name: a1010
                    alias: a1010
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 4th Oct
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OFNOAA4
                        changeLogNumber: '0'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutFormData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /rm-20-rm/services/apexrest/formdata/v1:
    put:
      tags:
        - default
      summary: Exception - JSON Mapping not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                records:
                  - externalId: '123'
                    id: ''
                    name: a100000
                    alias: a100000
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 4th Oct
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OBs7AAG
                        changeLogNumber: '0'
                  - externalId: '234'
                    id: a0h5g000002z4fVAAQ
                    name: a10010
                    alias: a10010
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 4th Oct
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OBtZAAW
                        changeLogNumber: '1'
                  - externalId: '345'
                    id: a0h5g000002zARTAA2
                    name: a1010
                    alias: a1010
                    messageAfterSubmission: Thank you for taking the time to complete this form!
                    description: This form was inserted through API on 4th Oct
                    status: Draft
                    formVersion:
                      - versionid: a0g5g000002OFNOAA4
                        changeLogNumber: '0'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: OAuth {{access_token}}
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: objectType
          in: query
          schema:
            type: string
          example: PutFormData
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
